### ISSUE TITLE
Error creating proof with large abi / input 

### ISSUE THREAD

**Issue by Ian-Bright** [socathie/hello-noir-ui#8]
Hi there, appreciate the template you have put together. I was able to get the x / y proof example to run in the browser but when using a larger proof input (in this case a 32 byte hex string and a number array of length 15) I get the following error when generating the proof:

```
aztec_backend.js:481 panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.
RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.
```

I'm digging into the packages but have not had any luck so far. Any familiarity with this problem?

**Comment by socathie** [comment]
Hi @Ian-Bright, so great that you are using my boilerplate!

I looked into the issue a bit and created a new branch [feat/worker](https://github.com/socathie/hello-noir-ui/tree/feat/worker) to handle the issue. Can you please test it out to see if it works on your circuit?

Please also pull/apply some of the changes I made on the main branch, which updated the `npm run copy:all` command. The README also now reminds users that `circSize` in `src/setup_generic_prover.ts` needs to be updated for bigger circuit.

**Comment by Ian-Bright** [comment]
Hey @socathie thanks for the reply! It appears to work now, can't thank you enough! I just need to verify the proof in the frontend for my use case. I grabbed the code for the verifier inside of `@noir-lang/barretenberg` and tried implementing it the way you implemented the generic prover. Verification of the proof does not seem to work so in the process of debugging right now.

Did you ever test in browser verification not involving a smart contract?

**Comment by socathie** [comment]
No I haven't. Usually verifying in the browser is not my use case. But I would be very interested to see the solution and you are much welcome to make a PR to include that part of the script if you work it out!

For now, I will merge `feat/worker` into `master` and consider this issue closed 🙏🏼
